"""Update users table

Revision ID: fd86cad92046
Revises: fc6a3d4ef9be
Create Date: 2025-05-13 19:11:01.174486

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fd86cad92046"
down_revision: Union[str, None] = "fc6a3d4ef9be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
